question_creation_task:
  description: >
    Create a unique coding question about the topic {topic} and difficulty {difficulty} and have a story. 
    Custom Requirements are {custom_requirements}
  expected_output: >
    The response should be a valid object that can be parsed into the specified format.
    Make sure to include all required fields and follow the exact structure.
  agent: question_creator